### ISSUE TITLE
how to use it with esbuild

### ISSUE THREAD

**Issue by nolotus** [openpgpjs/argon2id#1]
Thanks to the person who wrote this library.
But I have some rookie questions to ask
My esbuild configuration is as follows 
Server side
esbuild server/index.js --loader:.jsx --loader:.svg=file --bundle --outdir=build --platform=node --packages=external
Client
esbuild web/index.jsx --define:global=window --loader:.jsx --loader:.wasm=file --splitting --format=esm --loader:.svg=text --bumule -- outdir=public
Actually it is outputting wasm as a file.
On the server side I am prompted with the error 
[ERR_REQUIRE_ESM]: G:\nolo\node_modules\argon2id\index.js's ES module require() is not supported.
Please change require in G:\nolo\node_modules\argon2id\index.js to dynamic import(), and all CommonJS modules will work.
The server-side related code is as follows
import loadArgon2idWasm from 'argon2id';
const argon2id = await loadArgon2idWasm();
    console.log('argon2id', argon2id);
    const hashedPassword = argon2id({
      password: new Uint8Array(password),
      salt: salt,
      concurrency: 4,
      pass: 3.
      memory size: 2 ** 16,,
    }).

On the front end it will remind me that
no_simd_default is not a function
The code after I check the browser packaging is as follows
// node_modules/argon2id/dist/no-simd.wasm
var no_simd_default = ". /no-simd-XPSW4TIW.wasm";

// node_modules/argon2id/index.js
var loadWasm = async () => setupWasm(
  (instanceObject) => simd_default(instanceObject)
  (instanceObject) => no_simd_default(instanceObject)
).
var argon2id_default = loadWasm;
How can I use this library under esbuild?

**Comment by larabr** [comment]
Hey, I'm not familair with esbuild, I've only used rollup and webpack which provide some plugins to bundle wasm.
It looks like esbuild might have something similar: https://esbuild.github.io/plugins/#webassembly-plugin . See if that works [out of the box](https://github.com/openpgpjs/argon2id#usage).
