### ISSUE TITLE
tagLength

### ISSUE THREAD

**Issue by OfficialCRUGG** [openpgpjs/argon2id#2]
Why do I need to specify a tagLength to generate a hash? What do I put there? This is not in the usage guide...

**Comment by malobre** [comment]
The `tagLength` is the size of the hash output in bytes, the recommended default in the [argon2 spec (section 9, bullet point 6)](https://github.com/P-H-C/phc-winner-argon2/blob/f57e61e19229e23c4445b85494dbf7c07de721cb/argon2-specs.pdf) is ~~`32`~~.

Edit: The spec actually recommends 128 bits (16 bytes) as a default, their CLI defaults to 32 bytes.
